<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <Platforms>AnyCPU;x86</Platforms>
    <ApplicationIcon>assets\jaiseqx_icon_HSx_icon.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="assets\jaiseqx_icon_HSx_icon.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Be.IO" Version="1.0.0" />
    <PackageReference Include="Veldrid.ImageSharp" Version="4.9.0" />
    <PackageReference Include="Veldrid.ImGui" Version="5.72.0" />
    <PackageReference Include="Veldrid.StartupUtilities" Version="4.9.0" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Bass.Net">
      <HintPath>nonfree\Bass.Net.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <None Update="Arial.ttf">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="assets\jaiseqx.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="bass.dll">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
