<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <Platforms>AnyCPU;x86</Platforms>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="jaudio\archive\" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Bass.Net">
      <HintPath>..\Bass.Net.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
